In [16]:
import torch
from torch import nn
import d2lzh_pytorch as d2l

In [19]:
def corr2d_multi_in(X, K):
    res = d2l.corr2d(X[0, :, :], K[0, :, :])
    for i in range(1,X.shape[0]):
        res += d2l.corr2d(X[i,: ,: ],K[i, :, :])
    return res

X = torch.tensor([[[0, 1, 2], 
                   [3, 4, 5], 
                   [6, 7, 8]],
 [[1, 2, 3], 
  [4, 5, 6], 
  [7, 8, 9]]])

K = torch.tensor([[[0, 1], [2, 3]], [[1, 2], [3, 4]]])

corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [20]:
def corr2d_multi_in_out(X, K):
    return torch.stack([corr2d_multi_in(X, k) for k in K])

In [21]:
K = torch.stack([K,K+1,K+2])
K.shape

torch.Size([3, 2, 2, 2])

In [22]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [32]:
def corr2d_multi_in_out_1x1(X,K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.view(c_i, h * w)
    K = K.view(c_o,c_i)
    Y = torch.mm(K, X)
    return Y.view(c_o, h, w)

In [34]:
X = torch.rand(3, 3, 3) 
K = torch.rand(2, 3, 1, 1)
Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K) 
(Y1 - Y2).norm().item() < 1e-6
print(Y1)
print(Y2)

tensor([[[1.7760, 1.3442, 1.3708],
         [1.4386, 1.1136, 1.2912],
         [1.0717, 1.2396, 0.2213]],

        [[0.9926, 0.8415, 0.9452],
         [0.8826, 0.8930, 0.7351],
         [0.5341, 0.8290, 0.1655]]])
tensor([[[1.7760, 1.3442, 1.3708],
         [1.4386, 1.1136, 1.2912],
         [1.0717, 1.2396, 0.2213]],

        [[0.9926, 0.8415, 0.9452],
         [0.8826, 0.8930, 0.7351],
         [0.5341, 0.8290, 0.1655]]])
