# Basic

In [5]:
import torch

In [6]:
X = torch.empty
print(X)

<built-in method empty of type object at 0x00007FFC87690910>


In [7]:
x = torch.rand(5, 3)
print(x)


tensor([[0.9566, 0.7254, 0.9821],
        [0.0562, 0.9974, 0.5946],
        [0.0461, 0.2326, 0.7921],
        [0.4454, 0.0241, 0.1348],
        [0.2172, 0.7431, 0.9156]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = torch.ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype = torch.float)
print(x)


tensor([[-0.9876,  0.5295, -1.8869],
        [ 1.5363, -0.4903,  1.8600],
        [-1.2713,  0.3381,  1.3557],
        [ 0.3017, -1.4481,  0.3850],
        [ 1.3824,  0.2733,  0.8300]])


In [13]:
print(x.size())

torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)
#方法二
print(torch.add(x, y))

#方法三
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

#方法四
y.add_(x)
print(y)

tensor([[-6.0053e-01,  5.8556e-01, -1.3120e+00],
        [ 2.0245e+00,  1.5017e-04,  1.9451e+00],
        [-1.0181e+00,  7.9899e-01,  1.6589e+00],
        [ 1.2799e+00, -1.3049e+00,  1.1789e+00],
        [ 2.1514e+00,  3.1487e-01,  1.6993e+00]])
tensor([[-6.0053e-01,  5.8556e-01, -1.3120e+00],
        [ 2.0245e+00,  1.5017e-04,  1.9451e+00],
        [-1.0181e+00,  7.9899e-01,  1.6589e+00],
        [ 1.2799e+00, -1.3049e+00,  1.1789e+00],
        [ 2.1514e+00,  3.1487e-01,  1.6993e+00]])
tensor([[-6.0053e-01,  5.8556e-01, -1.3120e+00],
        [ 2.0245e+00,  1.5017e-04,  1.9451e+00],
        [-1.0181e+00,  7.9899e-01,  1.6589e+00],
        [ 1.2799e+00, -1.3049e+00,  1.1789e+00],
        [ 2.1514e+00,  3.1487e-01,  1.6993e+00]])
tensor([[-6.0053e-01,  5.8556e-01, -1.3120e+00],
        [ 2.0245e+00,  1.5017e-04,  1.9451e+00],
        [-1.0181e+00,  7.9899e-01,  1.6589e+00],
        [ 1.2799e+00, -1.3049e+00,  1.1789e+00],
        [ 2.1514e+00,  3.1487e-01,  1.6993e+00]])


In [15]:
print(x[:, 1])

tensor([ 0.5295, -0.4903,  0.3381, -1.4481,  0.2733])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
print(x.size(), y.size())

z = x.view(-1, 8)
print(x.size(), z.size())

torch.Size([4, 4]) torch.Size([16])
torch.Size([4, 4]) torch.Size([2, 8])


In [17]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.2495])
0.24952185153961182


In [18]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [21]:
np.add(a, 1, out=a)
print(a)
print(b)
#将numpy数组+1并观察上题中张量的变化

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [22]:
x = torch.ones(2, 3, requires_grad=True)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


# AutoDiff

In [23]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [24]:
z = y * y *3
out = z.mean()
print(z)
print(out)


tensor([[27., 27., 27.],
        [27., 27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [25]:
out.backward()

In [26]:
print(x.grad)
print(x)


tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [27]:
x = torch.ones(3, requires_grad=True)

y = x * 2
while y.data.norm()<1000:
    y = y * 2

print(y)

tensor([1024., 1024., 1024.], grad_fn=<MulBackward0>)


In [28]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


# 神经网络


In [37]:
from torch import nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 26.定义①的卷积层，输入为32x32的图像，卷积核大小5x5卷积核种类6
        self.conv1 = nn.Conv2d(3, 6, 5)
        # 27.定义③的卷积层，输入为前一层6个特征，卷积核大小5x5，卷积核种类16
        self.conv2 = nn.Conv2d(6, 16, 5)
        # 28.定义⑤的全链接层，输入为16*5*5，输出为120
        self.fc1 = nn.Linear(16 * 5 * 5, 120)  # 6*6 from image dimension
        # 29.定义⑥的全连接层，输入为120，输出为84
        self.fc2 = nn.Linear(120, 84)
        # 30.定义⑥的全连接层，输入为84，输出为10
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # 31.完成input-S2，先卷积+relu，再2x2下采样
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # 32.完成S2-S4，先卷积+relu，再2x2下采样
        x = F.max_pool2d(F.relu(self.conv2(x)), 2) #卷积核方形时，可以只写一个维度
        # 33.将特征向量扁平成列向量
        x = x.view(-1, 16 * 5 * 5)
        # 34.使用fc1+relu
        x = F.relu(self.fc1(x))
        # 35.使用fc2+relu
        x = F.relu(self.fc2(x))
        # 36.使用fc3
        x = self.fc3(x)
        return x
net = Net()
print(net)

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [38]:
params = list(net.parameters())
print(len(params))


10


In [39]:
print(params[0].size())

torch.Size([6, 3, 5, 5])


In [41]:
input = torch.randn(1, 3, 32, 32)
out = net(input)
print(out)

tensor([[ 0.0371, -0.0965,  0.0160, -0.0250,  0.0453, -0.1056,  0.0480,  0.0398,
         -0.0112,  0.1009]], grad_fn=<AddmmBackward>)


In [42]:
net.zero_grad()

In [43]:
out.backward(torch.randn(1, 10))

In [44]:
criterion = nn.MSELoss()

In [46]:
target = torch.randn(10)
target = target.view(1, -1)
output = net(input)
loss = criterion(output, target)
print(loss)

tensor(0.5312, grad_fn=<MseLossBackward>)


In [47]:
net.zero_grad()
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])


In [48]:
loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad after backward
tensor([-0.0102,  0.0112, -0.0071,  0.0206,  0.0017,  0.0049])


In [49]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.01)

In [50]:
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()

# 更新权重
optimizer.step()

In [51]:
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()

# 更新权重
optimizer.step()

In [52]:
trainset = cifar(root = './input/cifar10', segmentation='train', transforms=transform)
testset = cifar(root = './input/cifar10', segmentation='test', transforms=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,shuffle=True, num_workers=2)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

NameError: name 'cifar' is not defined

In [53]:
net2 = Net()


In [54]:
criterion2 = nn.CrossEntropyLoss()

In [55]:
optimizer2 = optim.SGD(net2.parameters(), lr=0.001, momentum=0.9)


In [56]:
for epoch in range(2):

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # 获取X,y对
        inputs, labels = data

        # 51.初始化梯度
        optimizer2.zero_grad()

        # 52.前馈
        outputs = net2(inputs)
        # 53.计算损失
        loss = criterion2(outputs, labels)
        # 54.计算梯度
        loss.backward()
        # 55.更新权值
        optimizer2.step()

        # 每2000个数据打印平均代价函数值
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print('[%d, %5d] loss: %.3f' %
                  (epoch + 1, i + 1, running_loss / 2000))
            running_loss = 0.0

print('Finished Training')

NameError: name 'trainloader' is not defined

In [57]:
dataiter = iter(testloader)
images, labels = dataiter.next()

# print images
imshow(torchvision.utils.make_grid(images))
print('GroundTruth: ', ' '.join('%5s' % classes[labels[j]] for j in range(4)))

NameError: name 'testloader' is not defined

In [58]:
outputs = net2(images)

_, predicted = torch.max(outputs, 1)

print('Predicted: ', ' '.join('%5s' % classes[predicted[j]]
                              for j in range(4)))

NameError: name 'images' is not defined

In [59]:
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        outputs = net2(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

print('Accuracy of the network on the 10000 test images: %d %%' % (
    100 * correct / total))

NameError: name 'testloader' is not defined

In [60]:
PATH = './cifar_net.pth'
torch.save(net.state_dict(), PATH)

In [ ]:
pretrained_net = torch.load(PATH)


In [ ]:
net3 = Net()
net3.load_state_dict(pretrained_net)