In [50]:
import torch
import numpy as np

In [11]:
print(torch.__version__)

1.3.1


In [18]:
x = torch.empty(5,3)
print(x)
x = torch.rand(5,3)
print(x)
x = torch.zeros(5,3)
print(x)
x = torch.tensor([5,3,1])
print(x)
x = x.new_zeros(5,3,dtype=torch.float64)
print(x)
x = torch.randn_like(x, dtype=torch.float)


print(x.size())
print(x.shape)

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.3410, 0.7327, 0.3068],
        [0.4569, 0.2367, 0.5908],
        [0.2814, 0.7593, 0.7641],
        [0.1662, 0.4344, 0.9748],
        [0.1368, 0.9394, 0.5406]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([5, 3, 1])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
torch.Size([5, 3])
torch.Size([5, 3])


In [26]:
y = torch.rand(5,3)
print(x + y)
print(torch.add(x,y))
y.add_(x)

tensor([[ 0.1624, -1.3907,  0.1528],
        [ 0.1153,  0.1851, -0.6381],
        [ 0.2896,  1.4768,  2.2509],
        [-0.0694, -0.0789,  1.3651],
        [ 0.7913,  1.4525, -1.2430]])
tensor([[ 0.1624, -1.3907,  0.1528],
        [ 0.1153,  0.1851, -0.6381],
        [ 0.2896,  1.4768,  2.2509],
        [-0.0694, -0.0789,  1.3651],
        [ 0.7913,  1.4525, -1.2430]])


tensor([[ 0.1624, -1.3907,  0.1528],
        [ 0.1153,  0.1851, -0.6381],
        [ 0.2896,  1.4768,  2.2509],
        [-0.0694, -0.0789,  1.3651],
        [ 0.7913,  1.4525, -1.2430]])

In [29]:
y = x[0, :]
print(x)
y += 1
print(y)
print(x[0, :])
print(y.size())

tensor([[ 2.0460,  0.1772,  1.6092],
        [-0.6885, -0.1808, -1.5937],
        [-0.6299,  1.1603,  2.1057],
        [-0.7563, -0.7095,  0.7691],
        [ 0.7429,  0.5486, -1.7357]])
tensor([3.0460, 1.1772, 2.6092])
tensor([3.0460, 1.1772, 2.6092])
torch.Size([3])


In [32]:
torch.gather(x,1,torch.Tensor([1,2]))

RuntimeError: Expected object of scalar type Long but got scalar type Float for argument #3 'index' in call to _th_gather

In [35]:
y = x.view(15)
z = x.view(-1,5)
print(x.size(),y.size(),z.size())
print(x)
y+=1
print(y)

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])
tensor([[ 4.0460,  2.1772,  3.6092],
        [ 0.3115,  0.8192, -0.5937],
        [ 0.3701,  2.1603,  3.1057],
        [ 0.2437,  0.2905,  1.7691],
        [ 1.7429,  1.5486, -0.7357]])
tensor([5.0460, 3.1772, 4.6092, 1.3115, 1.8192, 0.4063, 1.3701, 3.1603, 4.1057,
        1.2437, 1.2905, 2.7691, 2.7429, 2.5486, 0.2643])


In [37]:
# clone 可以返回副本
x_cp = x.clone().view(15)
x-=1
print(x)
print(x_cp)

tensor([[ 3.0460,  1.1772,  2.6092],
        [-0.6885, -0.1808, -1.5937],
        [-0.6299,  1.1603,  2.1057],
        [-0.7563, -0.7095,  0.7691],
        [ 0.7429,  0.5486, -1.7357]])
tensor([ 4.0460,  2.1772,  3.6092,  0.3115,  0.8192, -0.5937,  0.3701,  2.1603,
         3.1057,  0.2437,  0.2905,  1.7691,  1.7429,  1.5486, -0.7357])


In [39]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2283])
0.22826652228832245


In [41]:
x = torch.rand(4,4)
print(x)
print(torch.trace(x))
print(torch.diag(x))
print(torch.triu(x))


tensor([[0.3466, 0.9969, 0.5053, 0.6985],
        [0.9589, 0.3639, 0.9012, 0.7449],
        [0.4137, 0.7636, 0.7879, 0.3188],
        [0.7238, 0.4013, 0.5059, 0.2376]])
tensor(1.7361)
tensor([0.3466, 0.3639, 0.7879, 0.2376])
tensor([[0.3466, 0.9969, 0.5053, 0.6985],
        [0.0000, 0.3639, 0.9012, 0.7449],
        [0.0000, 0.0000, 0.7879, 0.3188],
        [0.0000, 0.0000, 0.0000, 0.2376]])


In [44]:
#broadcast
x = torch.arange(1, 3).view(1, 2)
print(x) 
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y) 

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [49]:
a = torch.ones(5)
b = a.numpy()
print(b)
a += 1
print(a,b)

[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [53]:

a = np.ones(5)
b = torch.from_numpy(a)
print(a, b) 
a += 1
print(a, b) 
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [55]:
c = torch.tensor(a)
a+=1
print(a,c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [56]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn) 

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [57]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [59]:
print(x.is_leaf,y.is_leaf)

True False


In [61]:
z = 3*y**2
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [68]:
a = torch.randn(2,2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [69]:
out.backward()

In [70]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [71]:
out2 = x.sum()
out2.backward()
print(x.grad)
out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [72]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [73]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [77]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x**2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2
print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # False
print(y3, y3.requires_grad) # True

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [78]:
y3.backward()
print(x.grad)

tensor(2.)


In [80]:
x = torch.ones(1,requires_grad=True)
print(x.data) # 还是⼀个tensor
print(x.data.requires_grad) # 但是已经是独⽴于计算图之外
print(x.requires_grad)
y = 2 * x 
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播
y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
True
tensor([100.], requires_grad=True)
tensor([2.])
