In [1]:
import torch
from torch import nn
from torch.nn import init

net = torch.nn.Sequential(nn.Linear(4,3),nn.ReLU(),nn.Linear(3,1))
print(net)
X = torch.rand(2,4)
Y = net(X).sum()


Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [2]:
print(type(net.parameters()))
for name,param in net.named_parameters():
    print(name, param.size())
for name,param in net.named_parameters():
    print(name, param.size(),type(param))

<class 'generator'>
0.weight torch.Size([3, 4])
0.bias torch.Size([3])
2.weight torch.Size([1, 3])
2.bias torch.Size([1])
0.weight torch.Size([3, 4]) <class 'torch.nn.parameter.Parameter'>
0.bias torch.Size([3]) <class 'torch.nn.parameter.Parameter'>
2.weight torch.Size([1, 3]) <class 'torch.nn.parameter.Parameter'>
2.bias torch.Size([1]) <class 'torch.nn.parameter.Parameter'>


In [3]:
class MyModel(nn.Module):
    def __init__(self,**kwargs):
        super(MyModel,self).__init__(**kwargs)
        self.weight1 = nn.Parameter(torch.rand(20,20))
        self.weight2 = torch.rand(20,20)
    def forward(self,x):
        pass
    
n = MyModel()

for name, param in n.named_parameters():
    print(name)
        

weight1


In [4]:
weight_0 = list(net.parameters())[0]
print(weight_0.data)
print(weight_0.grad)
Y.backward()
print(weight_0.grad)

tensor([[-0.1497, -0.0263,  0.1217,  0.3527],
        [ 0.2583,  0.3845, -0.3548,  0.2191],
        [-0.3976,  0.3350, -0.4193,  0.0892]])
None
tensor([[0.0000, 0.0000, 0.0000, 0.0000],
        [0.6519, 0.2569, 0.6350, 0.2291],
        [0.0000, 0.0000, 0.0000, 0.0000]])


In [7]:
for name,param in net.named_parameters():
    if 'weight' in name:
        init.normal_(param,mean=0,std=0.01)
        print(name,param.data)
    elif 'bias'in name:
        init.constant_(param,val=0)
        print(name,param.data)

0.weight tensor([[-0.0104,  0.0115,  0.0019,  0.0008],
        [-0.0104, -0.0017, -0.0101,  0.0135],
        [-0.0053,  0.0048,  0.0020, -0.0115]])
0.bias tensor([0., 0., 0.])
2.weight tensor([[ 0.0022,  0.0047, -0.0131]])
2.bias tensor([0.])


In [13]:
def normal_(tensor,mean=0,std=0.01):
    with torch.no_grad():
        return tensor.normal_(mean,std)

def init_weight(tensor):
    with torch.no_grad():
        tensor.uniform_(-10,10)
        tensor *= (tensor.abs()>5).float()
        
for name, param in net.named_parameters():
    if 'weight' in name:
        init_weight(param)
        print(name,param.data)
        

0.weight tensor([[-0.0000, -6.0880,  0.0000,  9.2712],
        [-8.8076, -5.6705,  5.8451,  0.0000],
        [ 0.0000, -6.7516,  8.9612, -7.0525]])
2.weight tensor([[-0., 0., 0.]])


In [18]:
for name, param in net.named_parameters():
    if 'bias' in name:
        param.data += 1
        print(name, param.data) 

0.bias tensor([3., 3., 3.])
2.bias tensor([3.])


In [22]:
linear = nn.Linear(1,1,bias=False)
net = nn.Sequential(linear,linear)
print(net)
for name, param in net.named_parameters():
    init.constant_(param, val=3)
    print(name, param.data)

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=False)
  (1): Linear(in_features=1, out_features=1, bias=False)
)
0.weight tensor([[3.]])


In [24]:
print(id(net[0]) == id(net[1]))
print(id(net[0].weight) == id(net[1].weight))

True
True


In [25]:
x = torch.ones(1,1)
y = net(x).sum()
print(y)
y.backward()
print(net[0].weight.grad)


tensor(9., grad_fn=<SumBackward0>)
tensor([[6.]])
